//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacture_DE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsBlocked { get; set; }
        public int CustomerId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual РольПользователя РольПользователя { get; set; }
    }
}
